### ISSUE TITLE
Linux-App doesnt start

### ISSUE THREAD

**Issue by Limbolindi** [jgraph/drawio-desktop#1018]
Hey, after the last Update it seems that darwio does have som access issues?

Draw.io Version: 18.1.3  -- installed with snap
`snap    2.55.5
snapd   2.55.5
series  16
ubuntu  20.04
kernel  5.13.0-44-generic
`
Ubuntu 20.04.4 LTS

`sudo chmode 1777 /dev/shm` btw doesn't do the trick ;D 

```

(drawio:36297): Gtk-WARNING **: 08:40:13.381: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(drawio:36297): Gtk-WARNING **: 08:40:13.385: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(drawio:36297): Gtk-WARNING **: 08:40:13.386: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
[36383:0528/084013.510809:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
08:40:13.568 › Checking for update
[36403:0528/084013.630475:ERROR:platform_shared_memory_region_posix.cc(250)] Creating shared memory in /dev/shm/.org.chromium.Chromium.5vJ4zb failed: Operation not permitted (1)
[36403:0528/084013.630628:ERROR:platform_shared_memory_region_posix.cc(253)] Unable to access(W_OK|X_OK) /dev/shm: Operation not permitted (1)
[36403:0528/084013.630706:FATAL:platform_shared_memory_region_posix.cc(255)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
08:40:14.105 › Update for version 18.1.3 is not available (latest version: 18.1.3, downgrade is disallowed).

```

`

**Comment by davidjgraph** [comment]
What binary is this?

**Comment by Limbolindi** [comment]
installed with snap

**Comment by alexwigforss** [comment]
Same problem here. On Ubuntu 19.10 if that matter. 
Got the deb package from https://github.com/jgraph/drawio-desktop/releases/tag/v18.1.3
If it helps i can post log later but it is nearly identical to Limbolindis
-edit turned out it was the snap version, got a little confused scince i tried the deb package first. Downloaded through resource center second time and that got me snap.

**Comment by Bruno-Ignaz** [comment]
On Ubuntu 22.04 too.
Also installed via snap https://github.com/jgraph/drawio-desktop/releases/tag/v18.1.3.

**Comment by linxux** [comment]
Same issue on Ubuntu 22.04.

White screen with nothing else.

**Comment by luctius** [comment]
Same with Kubuntu 21.10
Installed via snap, also version 18.1.3.

**Comment by davidjgraph** [comment]
Please no more "me too". We need technical debugging at this point.

**Comment by linxux** [comment]
> Please no more "me too". We need technical debugging at this point.

How to enable the console for further debugging log?

**Comment by davidjgraph** [comment]
Extras->Open dev tools

**Comment by eeintech** [comment]
> Extras->Open dev tools

The GUI does not open, where do you do that? Any other way?

**Comment by OrdoRefactorum** [comment]
Being on Ubuntu 20.04.4 LTS after trying without success as a regular user.
I tried starting the app via sudo where I got the following message:
```
mkdir: cannot create directory '/run/user/0': Permission denied
```
After creating that directory and doing sudo again:
```No protocol specified
[5393:0531/183424.013020:ERROR:ozone_platform_x11.cc(248)] Missing X server or $DISPLAY
[5393:0531/183424.013126:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.Aborted
```

The only thing I see in the logfile within the snap logs folder is (mind you, while having a working internet connection):
```
[2022-05-31 18:27:51.103] [error] @error@
 Error: net::ERR_INTERNET_DISCONNECTED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
    at SimpleURLLoaderWrapper.emit (node:events:390:28)
```
I hope this might help alleviate the issue.

**Comment by mKunzendorf** [comment]
On Ubuntu 18.04, i get the following error message when starting the app from via terminal:

```
$ drawio
[4879:0531/214136.012234:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
21:41:36.550 › Checking for update
21:41:36.720 › Generated new staging user ID: c2cfb705-6da4-568e-82e1-7be25dbb854c
21:41:37.900 › Update for version 18.1.3 is not available (latest version: 18.1.3, downgrade is disallowed).
[4909:0531/214137.989594:ERROR:platform_shared_memory_region_posix.cc(250)] Creating shared memory in /dev/shm/.org.chromium.Chromium.82lL9g failed: Operation not permitted (1)
[4909:0531/214137.989782:ERROR:platform_shared_memory_region_posix.cc(253)] Unable to access(W_OK|X_OK) /dev/shm: Operation not permitted (1)
[4909:0531/214137.989867:FATAL:platform_shared_memory_region_posix.cc(255)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at BrowserWindow.<anonymous> (/snap/drawio/155/resources/app.asar/electron.js:152:26)
    at BrowserWindow.emit (node:events:390:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at BrowserWindow.<anonymous> (/snap/drawio/155/resources/app.asar/electron.js:144:26)
    at BrowserWindow.emit (node:events:390:28)
```

**Comment by onip** [comment]
Hi all,

some additional info from my side.

1. with freshly installed `snap` (no update), I get the same console output as others
2. using the `.deb` from the releases page (Ubuntu 20.04 here) the app starts.

**Comment by Failxxx** [comment]
> Hi all,
> 
> some additional info from my side.
> 
>     1. with freshly installed `snap` (no update), I get the same console output as others
> 
>     2. using the `.deb` from the releases page (Ubuntu 20.04 here) the app starts.

Same here, it works using the `.deb` from the releases page (Ubuntu 18.04.6 LTS)

**Comment by davidjgraph** [comment]
I'd suggest to avoid to snap version, the electron support for it is pretty weak, we might remove it as a distro if this continues.

**Comment by eeintech** [comment]
> Hi all,
> 
> some additional info from my side.
> 
> 1. with freshly installed `snap` (no update), I get the same console output as others
> 2. using the `.deb` from the releases page (Ubuntu 20.04 here) the app starts.

AppImage works too!

**Comment by m-mohamedin** [comment]
the new version v19.0.0 should work in snap

**Comment by jdejoode** [comment]
Worked here:
`sudo snap remove drawio`
`sudo snap install drawio`

**Comment by jdejoode** [comment]
The error occurred after doing a snap refresh
