### ISSUE TITLE
Error on installing new version: TypeError: Cannot read properties of null (reading 'trim')

### ISSUE THREAD

**Issue by thohemp** [jgraph/drawio-desktop#1488]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Installing a new version results in following error:

```sh
09:33:52.442 › Install on explicit quitAndInstall
09:33:52.443 › Install: isSilent: false, isForceRunAfter: true
09:33:52.443 › Executing: which gksudo || which kdesudo || which pkexec || which beesu with args: 
/usr/bin/pkexec
09:33:52.453 › Error: TypeError: Cannot read properties of null (reading 'trim')
    at DebUpdater.spawnSyncLog (/opt/drawio/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:113:32)
    at DebUpdater.wrapSudo (/opt/drawio/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:91:27)
    at DebUpdater.doInstall (/opt/drawio/resources/app.asar/node_modules/electron-updater/out/DebUpdater.js:28:27)
    at DebUpdater.install (/opt/drawio/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:54:25)
    at DebUpdater.quitAndInstall (/opt/drawio/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:15:34)
    at Timeout._onTimeout (/opt/drawio/resources/app.asar/src/main/electron.js:1151:36)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
09:33:52.454 › @error@
 TypeError: Cannot read properties of null (reading 'trim')
    at DebUpdater.spawnSyncLog (/opt/drawio/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:113:32)
    at DebUpdater.wrapSudo (/opt/drawio/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:91:27)
    at DebUpdater.doInstall (/opt/drawio/resources/app.asar/node_modules/electron-updater/out/DebUpdater.js:28:27)
    at DebUpdater.install (/opt/drawio/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:54:25)
    at DebUpdater.quitAndInstall (/opt/drawio/resources/app.asar/node_modules/electron-updater/out/BaseUpdater.js:15:34)
    at Timeout._onTimeout (/opt/drawio/resources/app.asar/src/main/electron.js:1151:36)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

**To Reproduce**
1. Help -> Check for updates
2. Update available -> Download and install: Yes
3. Version is downloaded -> Install: Yes
4. Nothing happens except the command line output from above. 

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version x.y.z
v21.5.6 -> new (found) version: v22.0.2
**Desktop (please complete the following information):**
 - Ubuntu 20.04

**Additional context**

**Comment by Dominik-H** [comment]
Could be a different issue but on Windows 10 I have the same issue when auto updating from 22.0.0 to 22.0.3 with the following error in the log
`[2023-10-24 08:38:13.276] [error] @error@
 Error: New version 22.0.3 is not signed by the application owner: publisherNames: JGraph Ltd, raw info: {`
 
 followed by the certificate details.
