### ISSUE TITLE
Unable to launch drawio snap app on Ubuntu 24

### ISSUE THREAD

**Issue by gblondet117** [jgraph/drawio-desktop#1861]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/dev/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I have installed draw.io as a snap application on Ubuntu 24.04.1 LTS. When I run it in a terminal, I get the following error:

```
user@computer:~$ drawio

A JavaScript error occurred in the main process
Uncaught Exception:
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (node:os:365:11)
    at file:///snap/drawio/226/resources/app.asar/node_modules/atomically/dist/constants.js:10:29
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async node:electron/js2c/browser_init:2:128834
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:138:5)

(drawio:13155): Gtk-WARNING **: 11:54:58.319: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(drawio:13155): Gtk-WARNING **: 11:54:58.323: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(drawio:13155): Gtk-WARNING **: 11:54:58.323: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name

(drawio:13155): Gtk-WARNING **: 11:54:58.396: Theme parsing error: gtk-dark.css:1413:23: 'font-feature-settings' is not a valid property name

(drawio:13155): Gtk-WARNING **: 11:54:58.399: Theme parsing error: gtk-dark.css:3286:25: 'font-feature-settings' is not a valid property name

(drawio:13155): Gtk-WARNING **: 11:54:58.400: Theme parsing error: gtk-dark.css:3748:23: 'font-feature-settings' is not a valid property name
```
The problem is similar to (but not exactly the same) https://github.com/jgraph/drawio-desktop/issues/138

**To Reproduce**
1. In application center, search and install draw.io
2. Click on 'open'
3. See nothing
4. In a terminal, run drawio
5. See the error above.

**Expected behavior**
The drawio should start.

**Screenshots**

![Capture d’écran du 2024-09-09 12-02-53](https://github.com/user-attachments/assets/8f24d234-afba-4f29-a017-65c04f88e284)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 24.7.8

**Comment by gblondet117** [comment]
Hello,
I am still blocked by this error. 
Is there any solution or plan to fix this bug ? 
What can i do to bypass this problem and use DrawIO ?

**Comment by davidjgraph** [comment]
Use a distro other than snap?

**Comment by gblondet117** [comment]
I have just tried the AppImage (it worked well when I was on Ubuntu 20). I have downloaded the drawio-x86_64-24.7.8.AppImage and set it as executable.

I get 2 errors:
1. When I try to run the AppImage: drawio-x86_64-24.7.8.AppImage
```
[8134:0924/095642.524196:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_drawionvR0px/chrome-sandbox is owned by root and has mode 4755.
Trappe pour point d'arrêt et de trace (core dumped)
```
2. When I try with sudo:
[0924/095526.688327:FATAL:electron_main_delegate.cc(295)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trappe pour point d'arrêt et de trace


The problem may come from my configuration, but I don't really know. These errors could be correlated to my previous snap-related error.

**Comment by davidjgraph** [comment]
Yeah, you've got something different with permissions on the system, or on the device you're running the app from. I'm afraid we can't debug individual cases.

**Comment by gblondet117** [comment]
I do not know if it is only due to my configuration. I see similar problems related to Ubuntu 24, electron, the use of Wayland, and so on...
For instance: https://github.com/electron/electron/issues/41066

Do you know if I am the only one experiencing this kind of bug with snap apps or some AppImage files ?

**Comment by davidjgraph** [comment]
It might be that, but given the number of users we have, I'd expect more votes on the issue very quickly. If that happens, we can look again.

**Comment by buchbergerd** [comment]
I have the same problem. If I try to start drawio, nothing seems to happen. Using the terminal, I get this error message:

```
~$ drawio
A JavaScript error occurred in the main process
Uncaught Exception:
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (node:os:365:11)
    at file:///snap/drawio/226/resources/app.asar/node_modules/atomically/dist/constants.js:10:29
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async node:electron/js2c/browser_init:2:128834
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:138:5)

(drawio:197194): Gtk-WARNING **: 12:29:12.929: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(drawio:197194): Gtk-WARNING **: 12:29:12.932: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(drawio:197194): Gtk-WARNING **: 12:29:12.933: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
libGL error: MESA-LOADER: failed to open radeonsi (search paths /snap/drawio/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/drawio/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
[197282:0925/122913.041239:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[197282:0925/122913.041365:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[197282:0925/122913.041405:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[197282:0925/122913.042369:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[197282:0925/122913.042425:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[197282:0925/122913.042460:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[197282:0925/122913.042496:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[197282:0925/122913.042534:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[197282:0925/122913.045372:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[197282:0925/122913.045464:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[197282:0925/122913.045520:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[197282:0925/122913.046352:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[197282:0925/122913.046407:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[197282:0925/122913.046451:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[197282:0925/122913.046494:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[197282:0925/122913.046537:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[197282:0925/122913.047755:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization

(drawio:197194): Gtk-WARNING **: 12:29:13.048: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(drawio:197194): Gtk-WARNING **: 12:29:13.051: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(drawio:197194): Gtk-WARNING **: 12:29:13.052: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
libGL error: MESA-LOADER: failed to open radeonsi (search paths /snap/drawio/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/drawio/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
[197317:0925/122913.128247:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[197317:0925/122913.128351:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[197317:0925/122913.128386:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[197317:0925/122913.129160:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[197317:0925/122913.129204:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[197317:0925/122913.129236:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[197317:0925/122913.129273:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[197317:0925/122913.129308:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[197317:0925/122913.131985:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[197317:0925/122913.132053:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[197317:0925/122913.132087:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[197317:0925/122913.132806:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[197317:0925/122913.132856:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[197317:0925/122913.132928:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[197317:0925/122913.132962:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[197317:0925/122913.132995:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[197317:0925/122913.134778:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
MESA-LOADER: failed to open radeonsi (search paths /snap/drawio/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open kms_swrast (search paths /snap/drawio/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /snap/drawio/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load swrast driver

```

**Comment by MatthiasZerau** [comment]
Same for me on Ubuntu 22.04.5

```
% snap run drawio
A JavaScript error occurred in the main process
Uncaught Exception:
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (node:os:365:11)
    at file:///snap/drawio/226/resources/app.asar/node_modules/atomically/dist/constants.js:10:29
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async node:electron/js2c/browser_init:2:128834
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:138:5)

(drawio:2301877): Gtk-WARNING **: 14:28:18.507: Theme parsing error: gtk.css:1356:88: 'font-feature-settings' is not a valid property name
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/drawio/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
[2302193:0925/142819.307920:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2302193:0925/142819.308049:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2302193:0925/142819.308086:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[2302193:0925/142819.308668:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2302193:0925/142819.308711:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2302193:0925/142819.308745:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[2302193:0925/142819.308777:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[2302193:0925/142819.308810:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[2302193:0925/142819.311269:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2302193:0925/142819.311323:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2302193:0925/142819.311356:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[2302193:0925/142819.311815:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2302193:0925/142819.311857:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2302193:0925/142819.311886:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[2302193:0925/142819.311917:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[2302193:0925/142819.311948:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[2302193:0925/142819.343477:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization

(drawio:2301877): Gtk-WARNING **: 14:28:19.481: Theme parsing error: gtk.css:1356:88: 'font-feature-settings' is not a valid property name
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/drawio/226/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
[2302212:0925/142819.532482:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2302212:0925/142819.532599:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2302212:0925/142819.532640:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[2302212:0925/142819.533217:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2302212:0925/142819.533268:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2302212:0925/142819.533307:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[2302212:0925/142819.533345:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[2302212:0925/142819.533385:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[2302212:0925/142819.538005:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2302212:0925/142819.538088:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2302212:0925/142819.538139:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[2302212:0925/142819.538655:ERROR:angle_platform_impl.cc(44)] Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1083 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[2302212:0925/142819.538706:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[2302212:0925/142819.538738:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[2302212:0925/142819.538769:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[2302212:0925/142819.538799:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[2302212:0925/142819.540438:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
```

**Comment by daredem0** [comment]
Same issue for me on Ubuntu 22.04.01
`A JavaScript error occurred in the main process
Uncaught Exception:
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
`

**Comment by matheburg** [comment]
Same for me under Ubuntu 22.04.

The only way I could proceed was to install an older release, e.g.,
```shell
# https://github.com/jgraph/drawio-desktop/releases/tag/v24.6.4
sudo dpkg -i drawio-amd64-24.6.4.deb
```

PS. To raise the urgency of this issue, I see this on several systems (to be fair: all served from the same Ansible playbook, but one that is deployed to 1000s of PCs). It may help to check what you changed dependency-wise from 24.6 to 24.7, I guess.

**Comment by Roman2dot0** [comment]
Same for me under Ubuntu 24.04. snap drawio 24.7.17.

Met a same bug  in VSCode.
The problem was in js lib.

https://github.com/microsoft/vscode-remote-release/issues/9649#issuecomment-2038485154

**Comment by Roman2dot0** [comment]
Okay, simply fix

unpak app.asar ([project repo](https://github.com/electron/asar))

edit node_modules/atomically/dist/constants.js

and replace block with DEFAULT_USER_UID, DEFAULT_USER_GID with

```
try {
  var default_user_uid = os.userInfo().uid;
  var default_user_gid = os.userInfo().gid;
} catch {
  var default_user_uid = process.getuid();
  var default_user_gid = process.getgid();
}

const DEFAULT_USER_UID = default_user_uid;
const DEFAULT_USER_GID = default_user_gid;
``` 

pack into app.asar

repack snap follow the good instruction on [Reddit](https://www.reddit.com/r/linux/comments/10i6m19/i_figured_out_how_to_modify_installed_snaps/)

And snap version drawio is working.

**Comment by Roman2dot0** [comment]
@davidjgraph

**Comment by kekbaito** [comment]
This issue appears to also affect the NixOS drawio package: [https://search.nixos.org/packages?channel=24.11&show=drawio&from=0&size=50&sort=relevance&type=packages&query=drawio](https://search.nixos.org/packages?channel=24.11&show=drawio&from=0&size=50&sort=relevance&type=packages&query=drawio). 
It throws the same error.

**Comment by m-mohamedin** [comment]
Is this issue still affecting the latest version?

**Comment by Roman2dot0** [comment]
Yes.

**Comment by MichelMunoz** [comment]
@davidjgraph
> It might be that, but given the number of users we have, I'd expect more votes on the issue very quickly. If that happens, we can look again.

It is the https://github.com/electron/electron/issues/41066 pointed by another comment (the error log "`The SUID sandbox helper binary was found, but is not configured correctly.`" is the giveaway) ; all sorts of electron application are broken now.
Reproduced with draw.io appimage not working anymore after upgrade do 24.04 LTS which enforces apparmors (but working fine before the OS upgrade).

So one way or another (after electron [41066](https://github.com/electron/electron/issues/41066) above is fixed) the app will have to be apparmor compliant.

For now, a recipe **as a temporary workaround** for other impacted people, a recipe to run the appimage version unrestricted:
- as a sudo 
  - create a file `/etc/apparmor.d/my-drawio`
  - edit the file to have the following content:
```
abi <abi/4.0>,
include <tunables/global>

profile my-drawio /path/to/your/drawio-x86_64-25.0.2.AppImage flags=(default_allow) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/drawio>
}
```
(don't forget to customize the `/path/to/your/appimage` above)
  - then force load this profile (only this first time):
`sudo apparmor_parser -r /etc/apparmor.d/my-drawio`
- you can now launch your appimage

this is a one time file creation/setup, on all ulterior OS restart, the profile will be auto-loaded and the app can be launched (no sudo required)

**Comment by gblondet117** [comment]
Hi,

do you have any news about this issue. I am still unable to launch the snap app, even after updates. Is it a hard point or a specific case the app cannot be used ? Could we at least document it in installation instruction or something similar ?

Sincerely

**Comment by davidjgraph** [comment]
Read the comment directly above yours, it answers your question.

**Comment by stuart12** [comment]
Hello, the drawio snap version 28.0.6 does not open a window on Ubuntu 25.04 (Linux  6.14.0-28-generic #**28**-Ubuntu) when started by a user with home directory managed by systemd-homed 257. When I run draw.io (on the same machine) from an account not managed by systemd-homed, it starts without problem.  The element-desktop shows the same error. From an account managed by systemd-homed:
```
% /snap/bin/drawio
2025/08/22 23:01:33.091015 cmd_run.go:1412: WARNING: cannot start document portal: Message recipient disconnected from message bus without replying
A JavaScript error occurred in the main process
Uncaught Exception:
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (node:os:305:11)
    at file:///snap/drawio/252/resources/app.asar/node_modules/atomically/dist/constants.js:10:29
    at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
    at async node:electron/js2c/browser_init:2:135156
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:132:5)

(drawio:958028): Gtk-WARNING **: 23:01:33.495: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(drawio:958028): Gtk-WARNING **: 23:01:33.497: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(drawio:958028): Gtk-WARNING **: 23:01:33.498: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
[958028:0822/230133.542550:ERROR:dbus/object_proxy.cc:590] Failed to call method: org.freedesktop.Secret.Service.ReadAlias: object_path= /org/freedesktop/secrets: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.511" (uid=60262 pid=958028 comm="/snap/drawio/252/drawio --no-sandbox" label="snap.drawio.drawio (enforce)") interface="org.freedesktop.Secret.Service" member="ReadAlias" error name="(unset)" requested_reply="0" destination="org.freedesktop.secrets" (uid=60262 pid=8656 comm="/usr/bin/gnome-keyring-daemon --foreground --compo" label="unconfined")
libGL error: MESA-LOADER: failed to open radeonsi (search paths /snap/drawio/252/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/drawio/252/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
[958138:0822/230133.572914:ERROR:ui/gl/angle_platform_impl.cc:49] Display.cpp:1079 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1079 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[958138:0822/230133.573030:ERROR:ui/gl/gl_display.cc:408] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[958138:0822/230133.573056:ERROR:ui/gl/gl_display.cc:680] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[958138:0822/230133.573586:ERROR:ui/gl/angle_platform_impl.cc:49] Display.cpp:1079 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1079 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[958138:0822/230133.573617:ERROR:ui/gl/gl_display.cc:408] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[958138:0822/230133.573641:ERROR:ui/gl/gl_display.cc:680] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[958138:0822/230133.573666:ERROR:ui/gl/gl_display.cc:715] Initialization of all EGL display types failed.
[958138:0822/230133.573693:ERROR:ui/ozone/common/gl_ozone_egl.cc:26] GLDisplayEGL::Initialize failed.
[958138:0822/230133.575688:ERROR:ui/gl/angle_platform_impl.cc:49] Display.cpp:1079 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1079 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[958138:0822/230133.575731:ERROR:ui/gl/gl_display.cc:408] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[958138:0822/230133.575756:ERROR:ui/gl/gl_display.cc:680] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[958138:0822/230133.576276:ERROR:ui/gl/angle_platform_impl.cc:49] Display.cpp:1079 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
ERR: Display.cpp:1079 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[958138:0822/230133.576314:ERROR:ui/gl/gl_display.cc:408] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[958138:0822/230133.576351:ERROR:ui/gl/gl_display.cc:680] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[958138:0822/230133.576433:ERROR:ui/gl/gl_display.cc:715] Initialization of all EGL display types failed.
[958138:0822/230133.576477:ERROR:ui/ozone/common/gl_ozone_egl.cc:26] GLDisplayEGL::Initialize failed.
[958138:0822/230133.577601:ERROR:components/viz/service/main/viz_main_impl.cc:184] Exiting GPU process due to errors during initialization

(drawio:958028): Gtk-WARNING **: 23:01:33.608: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(drawio:958028): Gtk-WARNING **: 23:01:33.610: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(drawio:958028): Gtk-WARNING **: 23:01:33.610: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
MESA-LOADER: failed to open radeonsi (search paths /snap/drawio/252/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open kms_swrast (search paths /snap/drawio/252/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /snap/drawio/252/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load swrast driver
```

**Comment by Roman2dot0** [comment]
Fixed 

https://github.com/fabiospampinato/atomically/issues/13
