### ISSUE TITLE
Ubuntu install error message.

### ISSUE THREAD

**Issue by asifhg** [jgraph/drawio-desktop#529]
### Preflight Checklist

* [x]--> I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x]--> I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Error message while installing the debian package on ubuntu 20.04.

**To Reproduce**
1. wget -c https://github.com/jgraph/drawio-desktop/releases/download/v14.4.3/draw.io-amd64-14.4.3.deb ;
2. sudo dpkg -i draw.io-amd64-14.4.3.deb ;
3. Error message:
...
chmod: cannot access '/opt/drawio/chrome-sandbox': No such file or directory
Error in file "/usr/share/applications/org.kde.kdeconnect_open.desktop": "*/*" is an invalid MIME type ("*" is an unregistered media type)
...

**Expected behavior**
Install without error messages.

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.4.3

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**

**Comment by weyderfs** [comment]
Are you user have privilege to access `/opt` directory? If no you need check this, you error message sounds like _user permition_ .

**Comment by asifhg** [comment]
The steps to reproduce:
1. wget -c https://github.com/jgraph/drawio-desktop/releases/download/v14.4.3/draw.io-amd64-14.4.3.deb ;
2. sudo dpkg -i draw.io-amd64-14.4.3.deb ;
NOTE: Step 2 is executed as sudo. Doesn't sudo have permission write into /opt?

**Comment by perisage** [comment]
Same environment and the same problem. `sudo` does have the permission to write into `/opt` directory. Is there a solution to this problem？

**Comment by Martoni** [comment]
I have got the same problem on ubuntu focal : 

```
$ wget -c https://github.com/jgraph/drawio-desktop/releases/download/v14.4.3/draw.io-amd64-14.4.3.deb
$ sudo dpkg -i draw.io-amd64-14.4.3.deb
dpkg: warning: downgrading draw.io from 14.6.13 to 14.4.3
(Reading database ... 583260 files and directories currently installed.)
Preparing to unpack draw.io-amd64-14.4.3.deb ...
Unpacking draw.io (14.4.3) over (14.6.13) ...
Setting up draw.io (14.4.3) ...
chmod: cannot access '/opt/drawio/chrome-sandbox': No such file or directory
Error in file "/usr/share/applications/org.kde.kdeconnect_open.desktop": "*/*" is an invalid MIME type ("*" is an unregistered media type)
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu2) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for shared-mime-info (1.15-1) ...
```

If I launch drawio : 

```
$ drawio
Error: Exactly one file at a time
    at Object.<anonymous> (/usr/local/lib/node_modules/draw.io-export/index.js:27:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/draw.io-export/bin/drawio.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

My distribution : 

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

**Comment by davidjgraph** [comment]
This only seems to be for 14.4.3, anyone hit it on the latest?

**Comment by Martoni** [comment]
> This only seems to be for 14.4.3, anyone hit it on the latest?

Same for 14.6.13 : 

```
$ sudo dpkg -i /home/user/drawio-amd64-14.6.13.deb 
(Reading database ... 583260 files and directories currently installed.)
Preparing to unpack .../drawio-amd64-14.6.13.deb ...
Unpacking draw.io (14.6.13) over (14.4.3) ...
dpkg: warning: unable to delete old directory '/opt/draw.io/swiftshader': Directory not empty
dpkg: warning: unable to delete old directory '/opt/draw.io': Directory not empty
Setting up draw.io (14.6.13) ...
Error in file "/usr/share/applications/org.kde.kdeconnect_open.desktop": "*/*" is an invalid MIME type ("*" is an unregistered media type)
Processing triggers for shared-mime-info (1.15-1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu2) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...

$ drawio
Error: Exactly one file at a time
    at Object.<anonymous> (/usr/local/lib/node_modules/draw.io-export/index.js:27:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/draw.io-export/bin/drawio.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

```

**Comment by jdillard** [comment]
I get the following error on Ubuntu:

```[Errno 2] No such file or directory: '/opt/draw.io/drawio': '/opt/draw.io/drawio'```

I have a `/opt/drawio/drawio` though and I if I open that, it opens the draw.io app.
