### ISSUE TITLE
Current .deb (8.8.0-156) and .appimage builds SegFaults on Ubuntu 18.10 x64

### ISSUE THREAD

**Issue by duncwebb** [jgraph/drawio-desktop#61]
No symbols so the backtrace is of limited use...

$ gdb $(which draw.io)
GNU gdb (Ubuntu 8.2-0ubuntu1) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/draw.io...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/local/bin/draw.io 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000000a4fa30 in ?? ()
(gdb) bt
#0  0x0000000000a4fa30 in  ()
#1  0x00007ffff7d832b2 in node::http2::Http2Session::Callbacks::Callbacks(bool) () at /opt/draw.io/libnode.so
#2  0x00007ffff7d83375 in  () at /opt/draw.io/libnode.so
#3  0x00007ffff7fe398a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe0c8, env=env@entry=0x7fffffffe0d8) at dl-init.c:72
#4  0x00007ffff7fe3a89 in call_init (env=0x7fffffffe0d8, argv=0x7fffffffe0c8, argc=1, l=<optimized out>) at dl-init.c:30
#5  0x00007ffff7fe3a89 in _dl_init (main_map=0x7ffff7ffe190, argc=1, argv=0x7fffffffe0c8, env=0x7fffffffe0d8) at dl-init.c:119
#6  0x00007ffff7fd40ca in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#7  0x0000000000000001 in  ()
#8  0x00007fffffffe3e6 in  ()
#9  0x0000000000000000 in  ()

**Comment by duncwebb** [comment]
Building from sources the appimage works perfectly btw. so the problem looks to be down to the dependencies used at build time.

**Comment by duncwebb** [comment]
OK I've just installed the new .deb and it works perfectly. Great work.
